# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
users = User.create([
    {name: "Kristen Leach", email:"kristen@email.com", password: "password", image: "https://pbs.twimg.com/profile_images/971859707135586304/Kzt4JxUF_400x400.jpg"},
    {name: "Jessica Jones", email:"jones@email.com", password: "password", image: "https://pbs.twimg.com/profile_images/980702040996245504/szDLH7E7_400x400.jpg"},
    {name: "Walter White", email:"walt@email.com", password: "password", image: "https://pbs.twimg.com/profile_images/811218772191277056/nzXs6XZH_400x400.jpg"},
    {name: "Ben Solo", email:"kyloren@email.com", password: "password", image: "https://pbs.twimg.com/profile_images/943550682153357312/-8vFC8QP_400x400.jpg"},
    {name: "Takeshi Kovacs", email:"tak@email.com", password: "password", image: "https://cde.laprensa.e3.pe/ima/0/0/1/8/9/189264.jpg"},
    {name: "Leeloo Dallas", email:"leeloo@email.com", password: "password", image: "https://78.media.tumblr.com/636b9de8657217b3b45294090f34ddf7/tumblr_ouexsmFJO51tjoy0co1_500.jpg"},
    {name: "Rick Deckard", email:"iloverachel@email.com", password: "password", image: "https://pbs.twimg.com/profile_images/883308033194868736/7R1SfmEs_400x400.jpg"},
    {name: "Ziggy Stardust", email:"bowie4evr@email.com", password: "password", image: "https://cdn.fashionmagazine.com/wp-content/uploads/2016/01/david-bowie-aladdin-sane-ziggy-stardust-480x480-c-top.jpeg"},
    {name: "The Doctor", email:"doctorwho@email.com", password: "password", image: "http://www.thedoctorwhosite.co.uk/wp-images/doctorwho/characters/10-doctor.jpg"},
    {name: "Ellen Ripley", email:"alienssuck@email.com", password: "password", image: "http://www.writeups.org/wp-content/uploads/Ellen-Ripley-Alien-movies-Sigourney-Weaver.jpg"}
    ])

recipes = Recipe.create([
    {name: "No Bake Chocolate Cookies", description: "Chewy, chocolatey, peanut buttery oatmeal cookies that require no bake time!", ingredients: ["quick oats", "cocoa powder", "peanut butter", "sugar"], directions: "Mix all ingredients over low heat, drop by the TBS onto wax paper and let cool.", user_id: 1, image: "https://addapinch.com/wp-content/blogs.dir/3/files/2014/03/chocolate-no-bake-cookies-DSC_2853.jpg"},
    {name: "Whiskey on the Rocks", description: "A drink that helps you forget the past and stop caring about the future.", ingredients: ["cheap whiskey", "ice"], directions: "Put them in a glass and drink it already.", user_id: 2, image: "https://thumbs.dreamstime.com/b/glass-whiskey-rocks-selective-focus-image-light-glowing-glass-whiskey-ice-bottle-wood-bar-105314646.jpg"},
    {name: "Blue Sky Rock Candy", description: "It's not what it looks like; it's just ugar for christ's sake Skylar.", ingredients: ["sugar", "corn syrup", "blue food coloring", "peppermint extract"], directions: "Mix all but the peppermint extract in a beaker and heat to precisely 273 degrees fahrenheit. Allow the mixture to cool to 100 degrees and add the peppermint extract. Pour over wax paper and allow the mixture to cool. Shatter the candy into tiny pieces and sell at a 500% markup.", user_id: 3, image: "http://www.gastrotraveling.com/wp-content/uploads/2013/08/bluerockcandy.jpg"},
    {name: "Bantha Milk Smoothie", description: "Just a treat an old friend used to make for me after long days of training. Before you ask, no one knows why it's blue.", ingredients: ["Bantha milk", "Beebleberry ice cream"], directions: "Place the ingredients in a glass, reach out with the force to blend.", user_id: 4, image: "https://media3.popsugar-assets.com/files/2015/12/15/828/n/1922398/5d1b8057bc7a233d_bluemilkshake4.xxxlarge_2x.jpg"},
    {name: "Altered Wontons", description: "Fresh foods are scarce; use what you can find in this variation of a wonton.", ingredients: ["mixed vegetables", "tofu", "wonton wrappers", "egg wash"], directions: "Finely chop your vegetables and tofu. Stir-fry with soy sauce and ginger, or whatever you can find. Wrap them in the wonton wrappers and steam for 15 minutes.", user_id: 5, image: "https://2117e.https.cdn.softlayer.net/802117E/www.archanaskitchen.com/images/archanaskitchen/World_Soups/Vegetarian_Wonton_Soup_Indian_Chinese.jpg"},
    {name: "Chicken", description: "Chicken, good!", ingredients: ["freeze dried chicken substitute"], directions: "Chicken marbles into bowl, put into microwaver. Have chicken!", user_id: 6, image: "https://i.pinimg.com/originals/0e/03/87/0e03871df862780cadb9f1c015809902.jpg" },
    {name: "Mescal Worm Tacos", description: "Animals? They're all but extinct. But bugs-we've got plenty.", ingredients: ["meal worms", "serrano peppers" "corn tortillas", "salsa", "onions"], directions: "Fry up those meal worms with some salt and serrano peppers. The spice helps you forget you're eating bugs. Roll them up in a tortilla with the salsa and diced onions.", user_id: 7, image: "https://costamaya.com/wp-content/uploads/2018/01/maguey-worm-tacos.jpeg"},
    {name: "Shepherd's Pie", description: "An old favorite that reminds me of mum.", ingredients: ["ground beef", "peas", "carrots", "onions", "gravy", "mashed potatoes"], directions: "Cook the beef with the veg, and add the gravy. Pour it all in to the pie tin and top it with the mashed potatoes. Bake at 375* for one hour.", user_id: 8, image: "http://keyassets-p2.timeincuk.net/wp/prod/wp-content/uploads/sites/53/2017/03/Photo-Cottage-pie.jpg"},
    {name: "Fish Sticks and Custard", description: "When nothing else hits the spot, go for the fish fingers and custard.", ingredients: ["frozen fish fingers", "boxed custard"], directions: "Have a human cook the fish fingers for you. Dip the fish into the custard; fish custard!", user_id: 9, image: "https://static1.squarespace.com/static/559dc96be4b099333339097f/t/559dd115e4b0d1c3984b6b64/1436406048037/"},
    {name: "Alien Eggs", description: "Eat them before they eat you.", ingredients: ["xenomorph eggs", "nori"], directions: "Boil the eggs in a solution of vinegar and water for 24 hours. Yes, 24 hours. Unless you want what happened to Kane to happen to you. Peel the egg shells, wrap with nori and eat.", user_id: 10, image: "http://www.slashanddine.com/wp-content/uploads/2011/10/DSC_0014.jpg"}
])